//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbCancha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbCancha()
        {
            this.DbCancha_Horario = new HashSet<DbCancha_Horario>();
            this.DbCompeticion = new HashSet<DbCompeticion>();
        }
    
        public System.Guid IdCancha { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<System.Guid> IdDeporte { get; set; }
        public Nullable<System.TimeSpan> DuracionXPartido { get; set; }
        public Nullable<System.DateTime> FechaDeCreacion { get; set; }
        public Nullable<bool> EstadoCancha { get; set; }
        public string FranjaHoraria { get; set; }
        public string Nombre { get; set; }
        public string Precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbCancha_Horario> DbCancha_Horario { get; set; }
        public virtual DbDeporte DbDeporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbCompeticion> DbCompeticion { get; set; }
    }
}
