//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbCancha_Horario
    {
        public Nullable<System.Guid> IdCancha { get; set; }
        public Nullable<System.DateTime> Horario { get; set; }
        public Nullable<System.Guid> IdCliente { get; set; }
        public Nullable<bool> Abonada { get; set; }
        public Nullable<bool> FueCambiada { get; set; }
        public Nullable<System.Guid> IdEstadoReserva { get; set; }
        public System.Guid IdCancha_Horario { get; set; }
        public Nullable<int> CantReservas { get; set; }
    
        public virtual DbCancha DbCancha { get; set; }
        public virtual DbCliente DbCliente { get; set; }
        public virtual DbEstadoReserva DbEstadoReserva { get; set; }
    }
}
