//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbClasificacion
    {
        public System.Guid IdClasificacion { get; set; }
        public Nullable<int> CantDerrotas { get; set; }
        public Nullable<int> CantEmpates { get; set; }
        public Nullable<int> CantVictorias { get; set; }
        public Nullable<int> PartidosJugados { get; set; }
        public string NombreEquipo { get; set; }
        public Nullable<System.Guid> IdCompeticion { get; set; }
    
        public virtual DbCompeticion DbCompeticion { get; set; }
    }
}
