//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbCompeticion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbCompeticion()
        {
            this.DbClasificacion = new HashSet<DbClasificacion>();
            this.DbFixture = new HashSet<DbFixture>();
            this.DbEquipo = new HashSet<DbEquipo>();
        }
    
        public System.Guid IdCompeticion { get; set; }
        public Nullable<int> Cupos { get; set; }
        public Nullable<int> Cupos_min { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.Guid> IdFormato { get; set; }
        public string FranjaHoraria { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> PrecioInscripcion { get; set; }
        public Nullable<System.Guid> IdCancha { get; set; }
    
        public virtual DbCancha DbCancha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbClasificacion> DbClasificacion { get; set; }
        public virtual DbFormato DbFormato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbFixture> DbFixture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbEquipo> DbEquipo { get; set; }
    }
}
