//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbEquipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbEquipo()
        {
            this.DbJugador = new HashSet<DbJugador>();
            this.DbCompeticion = new HashSet<DbCompeticion>();
            this.DbFixture = new HashSet<DbFixture>();
        }
    
        public System.Guid IdEquipo { get; set; }
        public Nullable<int> CantAusencias { get; set; }
        public Nullable<System.Guid> IdCliente { get; set; }
        public Nullable<System.Guid> IdEstadoAsistencia { get; set; }
        public Nullable<System.DateTime> FechaDeCreacion { get; set; }
    
        public virtual DbCliente DbCliente { get; set; }
        public virtual DbEstadoAsistencia DbEstadoAsistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbJugador> DbJugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbCompeticion> DbCompeticion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbFixture> DbFixture { get; set; }
    }
}
