//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbFixture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbFixture()
        {
            this.DbEquipo = new HashSet<DbEquipo>();
        }
    
        public System.Guid IdFixture { get; set; }
        public Nullable<System.Guid> IdCompeticion { get; set; }
        public Nullable<System.Guid> IdEstadoFixture { get; set; }
        public string Resultado { get; set; }
    
        public virtual DbCompeticion DbCompeticion { get; set; }
        public virtual DbEstadoFixture DbEstadoFixture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbEquipo> DbEquipo { get; set; }
    }
}
