//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbJugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DbJugador()
        {
            this.DbPuntuacion = new HashSet<DbPuntuacion>();
            this.DbSanciones = new HashSet<DbSanciones>();
        }
    
        public System.Guid IdJugador { get; set; }
        public System.Guid IdEquipo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> PartidosJugados { get; set; }
        public Nullable<int> Mvp { get; set; }
        public string Apellido { get; set; }
    
        public virtual DbEquipo DbEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbPuntuacion> DbPuntuacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DbSanciones> DbSanciones { get; set; }
    }
}
