//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbPagos
    {
        public System.Guid IdPagos { get; set; }
        public Nullable<System.Guid> IdMensaje { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string EstadoPago { get; set; }
        public string IdTransaccion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual DbMensaje DbMensaje { get; set; }
    }
}
