//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeporteARContext : DbContext
    {
        public DeporteARContext()
            : base("name=DeporteARContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DbCancha> DbCancha { get; set; }
        public virtual DbSet<DbCancha_Horario> DbCancha_Horario { get; set; }
        public virtual DbSet<DbClasificacion> DbClasificacion { get; set; }
        public virtual DbSet<DbCliente> DbCliente { get; set; }
        public virtual DbSet<DbCompeticion> DbCompeticion { get; set; }
        public virtual DbSet<DbDeporte> DbDeporte { get; set; }
        public virtual DbSet<DbEquipo> DbEquipo { get; set; }
        public virtual DbSet<DbEstadoAsistencia> DbEstadoAsistencia { get; set; }
        public virtual DbSet<DbEstadoFixture> DbEstadoFixture { get; set; }
        public virtual DbSet<DbEstadoReserva> DbEstadoReserva { get; set; }
        public virtual DbSet<DbFixture> DbFixture { get; set; }
        public virtual DbSet<DbFormato> DbFormato { get; set; }
        public virtual DbSet<DbJugador> DbJugador { get; set; }
        public virtual DbSet<DbMensaje> DbMensaje { get; set; }
        public virtual DbSet<DbPagos> DbPagos { get; set; }
        public virtual DbSet<DbPuntuacion> DbPuntuacion { get; set; }
        public virtual DbSet<DbSanciones> DbSanciones { get; set; }
    }
}
