/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 25-ago-2025 16:50:13 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cancha_Deporte]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbCancha] DROP CONSTRAINT [FK_Cancha_Deporte]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cancha Horario_Cancha]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbCancha Horario] DROP CONSTRAINT [FK_Cancha Horario_Cancha]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cancha Horario_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbCancha Horario] DROP CONSTRAINT [FK_Cancha Horario_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cancha Horario_EstadoReserva]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbCancha Horario] DROP CONSTRAINT [FK_Cancha Horario_EstadoReserva]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Clasificacion_Competicion]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbClasificacion] DROP CONSTRAINT [FK_Clasificacion_Competicion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Competicion_Cancha]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbCompeticion] DROP CONSTRAINT [FK_Competicion_Cancha]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Competicion_Formato]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbCompeticion] DROP CONSTRAINT [FK_Competicion_Formato]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Equipo_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbEquipo] DROP CONSTRAINT [FK_Equipo_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Equipo_EstadoAsistencia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbEquipo] DROP CONSTRAINT [FK_Equipo_EstadoAsistencia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_EquipoCompeticion_Competicion]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbEquipoCompeticion] DROP CONSTRAINT [FK_EquipoCompeticion_Competicion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_EquipoCompeticion_Equipo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbEquipoCompeticion] DROP CONSTRAINT [FK_EquipoCompeticion_Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Fixture_Competicion]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbFixture] DROP CONSTRAINT [FK_Fixture_Competicion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Fixture_EstadoFixture]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbFixture] DROP CONSTRAINT [FK_Fixture_EstadoFixture]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_FixtureEquipo_Equipo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbFixtureEquipo] DROP CONSTRAINT [FK_FixtureEquipo_Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_FixtureEquipo_Fixture]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbFixtureEquipo] DROP CONSTRAINT [FK_FixtureEquipo_Fixture]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Jugador_Equipo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbJugador] DROP CONSTRAINT [FK_Jugador_Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mensaje_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbMensaje] DROP CONSTRAINT [FK_Mensaje_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pagos_Mensaje]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbPagos] DROP CONSTRAINT [FK_Pagos_Mensaje]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Puntuacion_Jugador]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbPuntuacion] DROP CONSTRAINT [FK_Puntuacion_Jugador]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Sanciones_Jugador]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DbSanciones] DROP CONSTRAINT [FK_Sanciones_Jugador]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbCancha]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbCancha]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbCancha Horario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbCancha Horario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbClasificacion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbClasificacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbCliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbCliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbCompeticion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbCompeticion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbDeporte]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbDeporte]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbEquipo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbEquipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbEquipoCompeticion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbEquipoCompeticion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbEstadoAsistencia]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbEstadoAsistencia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbEstadoFixture]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbEstadoFixture]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbEstadoReserva]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbEstadoReserva]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbFixture]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbFixture]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbFixtureEquipo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbFixtureEquipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbFormato]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbFormato]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbJugador]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbJugador]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbMensaje]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbMensaje]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbPagos]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbPagos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbPuntuacion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbPuntuacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DbSanciones]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DbSanciones]
GO

/* Create Tables */

CREATE TABLE [DbCancha]
(
	[IdCancha] uniqueidentifier NOT NULL,
	[Capacidad] int NULL,
	[IdDeporte] uniqueidentifier NULL,
	[DuracionXPartido] time(7) NULL,
	[FechaDeCreacion] datetime NULL DEFAULT GetDate(),
	[EstadoCancha] bit NULL,
	[FranjaHoraria] varchar(50) NULL,
	[Nombre] varchar(50) NULL,
	[Precio] varchar(50) NULL
)
GO

CREATE TABLE [DbCancha Horario]
(
	[IdCancha] uniqueidentifier NULL,
	[Horario] datetime NULL,
	[IdCliente] uniqueidentifier NULL,
	[Abonada] bit NULL,
	[FueCambiada] bit NULL,
	[IdEstadoReserva] uniqueidentifier NULL,
	[IdCancha-Horario] uniqueidentifier NOT NULL,
	[CantReservas] int NULL
)
GO

CREATE TABLE [DbClasificacion]
(
	[IdClasificacion] uniqueidentifier NOT NULL,
	[CantDerrotas] int NULL,
	[CantEmpates] int NULL,
	[CantVictorias] int NULL,
	[PartidosJugados] int NULL,
	[NombreEquipo] varchar(50) NULL,
	[IdCompeticion] uniqueidentifier NULL
)
GO

CREATE TABLE [DbCliente]
(
	[IdCliente] uniqueidentifier NOT NULL,
	[Nombre] varchar(50) NULL,
	[Telefeno] varchar(50) NULL
)
GO

CREATE TABLE [DbCompeticion]
(
	[IdCompeticion] uniqueidentifier NOT NULL,
	[Cupos] int NULL,
	[Cupos_min] int NULL,
	[Estado] varchar(50) NULL,
	[FechaCreacion] datetime NULL,
	[FechaInicio] datetime NULL,
	[IdFormato] uniqueidentifier NULL,
	[FranjaHoraria] varchar(50) NULL,
	[Frecuencia] int NULL,
	[Nombre] varchar(50) NULL,
	[PrecioInscripcion] decimal(18) NULL,
	[IdCancha] uniqueidentifier NULL
)
GO

CREATE TABLE [DbDeporte]
(
	[IdDeporte] uniqueidentifier NOT NULL,
	[Descripcion] varchar(50) NULL
)
GO

CREATE TABLE [DbEquipo]
(
	[IdEquipo] uniqueidentifier NOT NULL,
	[CantAusencias] int NULL,
	[IdCliente] uniqueidentifier NULL,
	[IdEstadoAsistencia] uniqueidentifier NULL,
	[FechaDeCreacion] datetime NULL DEFAULT GetDate()
)
GO

CREATE TABLE [DbEquipoCompeticion]
(
	[IdCompeticion] uniqueidentifier NOT NULL,
	[IdEquipo] uniqueidentifier NOT NULL
)
GO

CREATE TABLE [DbEstadoAsistencia]
(
	[IdEstadoAsistencia] uniqueidentifier NOT NULL,
	[Descripcion] varchar(50) NULL
)
GO

CREATE TABLE [DbEstadoFixture]
(
	[IdEstadoFixture] uniqueidentifier NOT NULL,
	[Descripcion] varchar(50) NULL
)
GO

CREATE TABLE [DbEstadoReserva]
(
	[IdEstadoReserva] uniqueidentifier NOT NULL,
	[Descripcion] varchar(50) NULL
)
GO

CREATE TABLE [DbFixture]
(
	[IdFixture] uniqueidentifier NOT NULL,
	[IdCompeticion] uniqueidentifier NULL,
	[IdEstadoFixture] uniqueidentifier NULL,
	[Resultado] varchar(50) NULL
)
GO

CREATE TABLE [DbFixtureEquipo]
(
	[IdFixture] uniqueidentifier NOT NULL,
	[IdEquipo] uniqueidentifier NOT NULL
)
GO

CREATE TABLE [DbFormato]
(
	[IdFormato] uniqueidentifier NOT NULL,
	[Descripcion] varchar(50) NULL
)
GO

CREATE TABLE [DbJugador]
(
	[IdJugador] uniqueidentifier NOT NULL,
	[IdEquipo] uniqueidentifier NOT NULL,
	[Nombre] varchar(50) NULL,
	[PartidosJugados] int NULL,
	[Mvp] int NULL,
	[Apellido] varchar(50) NULL
)
GO

CREATE TABLE [DbMensaje]
(
	[IdMensaje] uniqueidentifier NOT NULL,
	[IdCliente] uniqueidentifier NULL,
	[Contenido] text NULL,
	[EstadoEnvio] varchar(50) NULL,
	[FechaEnvio] datetime NULL,
	[FechaEstado] datetime NULL
)
GO

CREATE TABLE [DbPagos]
(
	[IdPagos] uniqueidentifier NOT NULL,
	[IdMensaje] uniqueidentifier NULL,
	[Monto] decimal(18) NULL,
	[EstadoPago] varchar(50) NULL,
	[IdTransaccion] varchar(50) NULL,
	[FechaCreacion] datetime NULL
)
GO

CREATE TABLE [DbPuntuacion]
(
	[IdPuntuacion] uniqueidentifier NOT NULL,
	[Descripcion] varchar(50) NULL,
	[Cantidad] int NULL,
	[IdJugador] uniqueidentifier NULL
)
GO

CREATE TABLE [DbSanciones]
(
	[IdSancion] uniqueidentifier NOT NULL,
	[Descripcion] varchar(50) NULL,
	[Cantidad] int NULL,
	[IdJugador] uniqueidentifier NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [DbCancha] 
 ADD CONSTRAINT [PK_Cancha]
	PRIMARY KEY CLUSTERED ([IdCancha] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cancha_Deporte] 
 ON [DbCancha] ([IdDeporte] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cancha_EstadoCancha] 
 ON [DbCancha] ([EstadoCancha] ASC)
GO

ALTER TABLE [DbCancha Horario] 
 ADD CONSTRAINT [PK_Table1]
	PRIMARY KEY CLUSTERED ([IdCancha-Horario] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cancha Horario_Cancha] 
 ON [DbCancha Horario] ([IdCancha] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cancha Horario_Cliente] 
 ON [DbCancha Horario] ([IdCliente] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cancha Horario_EstadoReserva] 
 ON [DbCancha Horario] ([IdEstadoReserva] ASC)
GO

ALTER TABLE [DbClasificacion] 
 ADD CONSTRAINT [PK_Clasificacion]
	PRIMARY KEY CLUSTERED ([IdClasificacion] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Clasificacion_Competicion] 
 ON [DbClasificacion] ([IdCompeticion] ASC)
GO

ALTER TABLE [DbCliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([IdCliente] ASC)
GO

ALTER TABLE [DbCompeticion] 
 ADD CONSTRAINT [PK_Competicion]
	PRIMARY KEY CLUSTERED ([IdCompeticion] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Competicion_Cancha] 
 ON [DbCompeticion] ([IdCancha] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Competicion_Formato] 
 ON [DbCompeticion] ([IdFormato] ASC)
GO

ALTER TABLE [DbDeporte] 
 ADD CONSTRAINT [PK_Deporte]
	PRIMARY KEY CLUSTERED ([IdDeporte] ASC)
GO

ALTER TABLE [DbEquipo] 
 ADD CONSTRAINT [PK_Equipo]
	PRIMARY KEY CLUSTERED ([IdEquipo] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Equipo_Cliente] 
 ON [DbEquipo] ([IdCliente] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Equipo_EstadoAsistencia] 
 ON [DbEquipo] ([IdEstadoAsistencia] ASC)
GO

ALTER TABLE [DbEquipoCompeticion] 
 ADD CONSTRAINT [PK_EquipoCompeticion]
	PRIMARY KEY CLUSTERED ([IdCompeticion] ASC,[IdEquipo] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_EquipoCompeticion_Competicion] 
 ON [DbEquipoCompeticion] ([IdCompeticion] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_EquipoCompeticion_Equipo] 
 ON [DbEquipoCompeticion] ([IdEquipo] ASC)
GO

ALTER TABLE [DbEstadoAsistencia] 
 ADD CONSTRAINT [PK_EstadoAsistencia]
	PRIMARY KEY CLUSTERED ([IdEstadoAsistencia] ASC)
GO

ALTER TABLE [DbEstadoFixture] 
 ADD CONSTRAINT [PK_EstadoFixture]
	PRIMARY KEY CLUSTERED ([IdEstadoFixture] ASC)
GO

ALTER TABLE [DbEstadoReserva] 
 ADD CONSTRAINT [PK_EstadoReserva]
	PRIMARY KEY CLUSTERED ([IdEstadoReserva] ASC)
GO

ALTER TABLE [DbFixture] 
 ADD CONSTRAINT [PK_Fixture]
	PRIMARY KEY CLUSTERED ([IdFixture] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Fixture_Competicion] 
 ON [DbFixture] ([IdCompeticion] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Fixture_EstadoFixture] 
 ON [DbFixture] ([IdEstadoFixture] ASC)
GO

ALTER TABLE [DbFixtureEquipo] 
 ADD CONSTRAINT [PK_FixtureEquipo]
	PRIMARY KEY CLUSTERED ([IdFixture] ASC,[IdEquipo] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_FixtureEquipo_Equipo] 
 ON [DbFixtureEquipo] ([IdEquipo] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_FixtureEquipo_Fixture] 
 ON [DbFixtureEquipo] ([IdFixture] ASC)
GO

ALTER TABLE [DbFormato] 
 ADD CONSTRAINT [PK_Formato]
	PRIMARY KEY CLUSTERED ([IdFormato] ASC)
GO

ALTER TABLE [DbJugador] 
 ADD CONSTRAINT [PK_Jugador]
	PRIMARY KEY CLUSTERED ([IdJugador] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Jugador_Equipo] 
 ON [DbJugador] ([IdEquipo] ASC)
GO

ALTER TABLE [DbMensaje] 
 ADD CONSTRAINT [PK_Mensaje]
	PRIMARY KEY CLUSTERED ([IdMensaje] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Mensaje_Cliente] 
 ON [DbMensaje] ([IdCliente] ASC)
GO

ALTER TABLE [DbPagos] 
 ADD CONSTRAINT [PK_Pagos]
	PRIMARY KEY CLUSTERED ([IdPagos] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Pagos_Mensaje] 
 ON [DbPagos] ([IdMensaje] ASC)
GO

ALTER TABLE [DbPuntuacion] 
 ADD CONSTRAINT [PK_Puntuacion]
	PRIMARY KEY CLUSTERED ([IdPuntuacion] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Puntuacion_Jugador] 
 ON [DbPuntuacion] ([IdJugador] ASC)
GO

ALTER TABLE [DbSanciones] 
 ADD CONSTRAINT [PK_Sanciones]
	PRIMARY KEY CLUSTERED ([IdSancion] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Sanciones_Jugador] 
 ON [DbSanciones] ([IdJugador] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [DbCancha] ADD CONSTRAINT [FK_Cancha_Deporte]
	FOREIGN KEY ([IdDeporte]) REFERENCES [DbDeporte] ([IdDeporte]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbCancha Horario] ADD CONSTRAINT [FK_Cancha Horario_Cancha]
	FOREIGN KEY ([IdCancha]) REFERENCES [DbCancha] ([IdCancha]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbCancha Horario] ADD CONSTRAINT [FK_Cancha Horario_Cliente]
	FOREIGN KEY ([IdCliente]) REFERENCES [DbCliente] ([IdCliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbCancha Horario] ADD CONSTRAINT [FK_Cancha Horario_EstadoReserva]
	FOREIGN KEY ([IdEstadoReserva]) REFERENCES [DbEstadoReserva] ([IdEstadoReserva]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbClasificacion] ADD CONSTRAINT [FK_Clasificacion_Competicion]
	FOREIGN KEY ([IdCompeticion]) REFERENCES [DbCompeticion] ([IdCompeticion]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbCompeticion] ADD CONSTRAINT [FK_Competicion_Cancha]
	FOREIGN KEY ([IdCancha]) REFERENCES [DbCancha] ([IdCancha]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbCompeticion] ADD CONSTRAINT [FK_Competicion_Formato]
	FOREIGN KEY ([IdFormato]) REFERENCES [DbFormato] ([IdFormato]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbEquipo] ADD CONSTRAINT [FK_Equipo_Cliente]
	FOREIGN KEY ([IdCliente]) REFERENCES [DbCliente] ([IdCliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbEquipo] ADD CONSTRAINT [FK_Equipo_EstadoAsistencia]
	FOREIGN KEY ([IdEstadoAsistencia]) REFERENCES [DbEstadoAsistencia] ([IdEstadoAsistencia]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbEquipoCompeticion] ADD CONSTRAINT [FK_EquipoCompeticion_Competicion]
	FOREIGN KEY ([IdCompeticion]) REFERENCES [DbCompeticion] ([IdCompeticion]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbEquipoCompeticion] ADD CONSTRAINT [FK_EquipoCompeticion_Equipo]
	FOREIGN KEY ([IdEquipo]) REFERENCES [DbEquipo] ([IdEquipo]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbFixture] ADD CONSTRAINT [FK_Fixture_Competicion]
	FOREIGN KEY ([IdCompeticion]) REFERENCES [DbCompeticion] ([IdCompeticion]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbFixture] ADD CONSTRAINT [FK_Fixture_EstadoFixture]
	FOREIGN KEY ([IdEstadoFixture]) REFERENCES [DbEstadoFixture] ([IdEstadoFixture]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbFixtureEquipo] ADD CONSTRAINT [FK_FixtureEquipo_Equipo]
	FOREIGN KEY ([IdEquipo]) REFERENCES [DbEquipo] ([IdEquipo]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbFixtureEquipo] ADD CONSTRAINT [FK_FixtureEquipo_Fixture]
	FOREIGN KEY ([IdFixture]) REFERENCES [DbFixture] ([IdFixture]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbJugador] ADD CONSTRAINT [FK_Jugador_Equipo]
	FOREIGN KEY ([IdEquipo]) REFERENCES [DbEquipo] ([IdEquipo]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbMensaje] ADD CONSTRAINT [FK_Mensaje_Cliente]
	FOREIGN KEY ([IdCliente]) REFERENCES [DbCliente] ([IdCliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbPagos] ADD CONSTRAINT [FK_Pagos_Mensaje]
	FOREIGN KEY ([IdMensaje]) REFERENCES [DbMensaje] ([IdMensaje]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbPuntuacion] ADD CONSTRAINT [FK_Puntuacion_Jugador]
	FOREIGN KEY ([IdJugador]) REFERENCES [DbJugador] ([IdJugador]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DbSanciones] ADD CONSTRAINT [FK_Sanciones_Jugador]
	FOREIGN KEY ([IdJugador]) REFERENCES [DbJugador] ([IdJugador]) ON DELETE No Action ON UPDATE No Action
GO
